language:
  - cpp
python:
  - "2.7"
compiler:
  - gcc
before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo apt-get -qq install $ sudo apt-get install git gcc g++ libjpeg-dev libxext-dev libx11-dev libgl1-mesa-dev libglu1-mesa-dev libpq-dev libpng12-dev xfonts-100dpi xfonts-75dpi msttcorefonts
  - git clone --depth 1 http://github.com/euslisp/jskeus jskeus
  - ln -sf ${CI_SOURCE_PATH} eus
  - cd jskeus
install:
  - make
script:
  - source .bashrc.eus
  - find irteus/test -iname "*.l" | grep -v unittest.l | xargs -n1 irteusgl
notifications:
  email:
    on_success: always
    on_failure: always
